### ISSUE TITLE
[Request] Tabs

### ISSUE THREAD

**Issue by blockiyt** [halfmoonui/halfmoon#106]
Something like this: https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior, it's great for Information boxes.

**Comment by OvermindDL1** [comment]
For note, tabs can be done without JS, I've done so with a set of radio inputs and labels to act as the switchers and tags for the CSS to show the right section, easily overall.  Even possible to be generic to the number of tabs as well.

**Comment by mrintangble** [comment]
@OvermindDL1 Would you illustrate us?
