### ISSUE TITLE
scrollTop function is not working

### ISSUE THREAD

**Issue by abhijeet-cn** [halfmoonui/halfmoon#107]
Hey, I am sure why this is happening. I was trying to create a scroll to top button and tried a lot of solutions from StackOverflow but nothing seems to work. 

` $("html, body").animate({ scrollTop: 0 }, "slow");`

Any help on this is appreciated. 
Thanks

**Comment by abdeljail** [comment]
Hey guys
`$('html, body').animate({scrollTop: 0},'slow');` : is perfectly valid code for an animated scroll
try this code:
`
body{
  height: 200vh;
}
`
`
<body>
<a  class="scroll-top">Scroll Up</a>
</body>
`
`
<script>
$(function() {
  $(".scroll-top").on("click", function(e){
       e.preventDefault();
       $('html, body').animate({scrollTop: 0}, 'slow');
  });
});
</script>
`

**Comment by abdeljail** [comment]
Hey guys
`$('html, body').animate({scrollTop: 0},'slow');`  :  is perfectly valid code for an animated scroll <br/>
try this code:
<br/>
![qj](https://user-images.githubusercontent.com/72315742/124180061-90e32480-daab-11eb-9225-3aea8f1f7f6b.PNG)

**Comment by Toby222** [comment]
Which doesn't help in explaining why it doesn't work for @abhijeet-cn, sadly.
Is the problem related to halfmoon? Or can you re-create it without the css?

**Comment by Looky1173** [comment]
Hello,

I was having the same issue. I found that you must scroll not on the `body` but on `.content-wrapper`, like so:
```js
$('.content-wrapper').animate({scrollTop: '0px'}, 1000);
```
This occurs thanks to how Halfmoon structures your page where the `body` will always take up exactly the full visible screen area and the page contents are themselves wrapped in `.page-wrapper > .content-wrapper`.

**Comment by abhijeet-cn** [comment]
Thanks this worked for me, I am closing the issue.
