### ISSUE TITLE
Flickering dark mode switch

### ISSUE THREAD

**Issue by neerajadhav** [halfmoonui/halfmoon#111]
I have made a hugo blog site using halfmoon css, everything is cool. But there is one problem in dark mode, when I refresh the page or go to some internal link then a flickering is observed while loading for a millisecond, which don't look professional. Is there any way to stop that...?

Link to my website: [neerajadhav.github.io](https://neerajadhav.github.io)

**Comment by Toby222** [comment]
What browser are you using?
I'm on Chrome and there's no flickering for me.

**Comment by neerajadhav** [comment]
I used Firefox as well as Microsoft edge, and the same is happening on chrome in my android device😕

**Comment by neerajadhav** [comment]
> I used Firefox as well as Microsoft edge, and the same is happening on chrome in my android device😕

![Project_07-30_Full HD 1080p_1.gif](https://user-images.githubusercontent.com/32135561/127635689-435f82d5-b704-4250-ad65-247b6fe0c038.gif)

**Comment by Toby222** [comment]
Hm.
Okay, I can get it on my phone, or on my desktop if I reload without cache.

I suppose you'd have to apply the `dark-mode` class server-side when needed to avoid the flashing from the theme swapping out?
