### ISSUE TITLE
Modal close event

### ISSUE THREAD

**Issue by thdoan** [halfmoonui/halfmoon#120]
How are you guys handling logic to kick off some logic when the modal is closed? I looked in the source and don't see a `dispatchEvent()` anywhere, so I was planning to create a mutation observer for this, but wanted to see some other solutions before I proceed.

**Comment by ksenginew** [comment]
Hi @notchris It looks like halfmoon is not in active development. I had created an active clone named **Fullmoon**. Please refer to https://github.com/halfmoonui/halfmoon/issues/116#issuecomment-1013674632 for more info.

You can report any issues [here](https://github.com/ksenginew/fullmoon/issues). And [contribute Fullmoon](https://github.com/ksenginew/fullmoon) to add this feature.

**Comment by thdoan** [comment]
@ksenginew glad you're picking up the mantle, but one suggestion though: maybe mention Halfmoon somewhere -- this word is nowhere to be found on https://github.com/ksenginew/fullmoon.

**Comment by ksenginew** [comment]
> @ksenginew glad you're picking up the mantle, but one suggestion though: maybe mention Halfmoon somewhere -- this word is nowhere to be found on https://github.com/ksenginew/fullmoon.

Oh I wanted to mention halfmoon. I had mentioned in main source files. But forgot to mention in readme. I'll do it as soon as possible.(with some readme improvements)
