### ISSUE TITLE
Sidebar, darkmode and modals are not automatically toggled as expected.

### ISSUE THREAD

**Issue by ScopesCodez** [halfmoonui/halfmoon#125]
[This video](https://capy-cdn.xyz/GHt64d5Y.webm) showcases my issue. Dark mode is not automatically enabled, thus I need to call `halfmoon.toggleDarkMode()` upon loading the page. And, the sidebar is auto opened as well. Finally, the "followers" modal is opened instantly without toggling it myself. And I cannot find a way to close it upon loading the page. I need help figuring out how to make everything work normally so my project won't look buggy to users.

**Comment by makerio90** [comment]
do you have `data-set-preferred-mode-onload="true"` in your `<body>` tag?

**Comment by ScopesCodez** [comment]
Just added it. However, now it just switched from dark mode to light mode and vice versa each time I reload the page. Meaning that's another issue, thus I'll just remove that.

**Comment by ScopesCodez** [comment]
I don't think [this](https://capy-cdn.xyz/FeJdLmzW.webm) is normal.

**Comment by ScopesCodez** [comment]
Turns out it was all just an issue with my reading skills. Didn't notice some important notes on both the documentation and my code. Finally, fixed everything.

**Comment by Supernova3339** [comment]
An easier solution here would be to just put comments to let you know which
is which and use the working solution. It’s working, just not the way you
expect it to work. Your ui looks awesome! Can’t wait to see what you’ve
made on release.
If there’s any way for me to make it easier for you, just switch the light
and dark class names around.
