### ISSUE TITLE
Will the project continue?

### ISSUE THREAD

**Issue by WellingtonFonseca** [halfmoonui/halfmoon#129]
hello, patreon is not working, i really want to support this project. Will there be continuity? if not, how can we continue? - google translate

**Comment by makerio90** [comment]
hello. this project seems abandoned, i don't know if it will ever receive more updates.
you may find interest in [bootsrap](https://getbootstrap.com/)

**Comment by WellingtonFonseca** [comment]
what a pity, I thought it was an amazing job
