### ISSUE TITLE
Halfmoon documentation isn't available anymore

### ISSUE THREAD

**Issue by webserviceXXL** [halfmoonui/halfmoon#132]
Official docs aren't available anymore. https://www.gethalfmoon.com/docs/

**Comment by xy0** [comment]
You're quick. I just refreshed my browser and got the new page too. 


Here's the Internet Archive link for the docs:
http://web.archive.org/web/20221005090349/https://www.gethalfmoon.com/docs/introduction/


I'd be down to re-host the HTML. Does anyone have it?

This is what we get for using a non-supported library. But please don't let this die, it's a great library!

**Comment by Supernova3339** [comment]
Here's what we can do. Let's fork it to an org, let's say HalfmoonUI+
We'll have the existing files, and someone will contact the devs to obtain
the source files for the website. We'll get JSDELIVR setup as an
appropriate cdn for the CSS/HTML, and we will add any PRs that might be
available and provide any merges. If anyone is interested, reply!

**Comment by Supernova3339** [comment]
Oh, one more thing. The site is written in python, it uses Django.

**Comment by Exordio** [comment]
> 

I think that the structure of the site can be taken from the archive. Styles and everything else is in the library. Django is completely unnecessary here. Just like any other backend. Unless you use DJANGO to manage content.

**Comment by webserviceXXL** [comment]
@halfmoonui Could you include static files of the documentation in this repo?

**Comment by Supernova3339** [comment]
Warning you now, that isn't the way to get it contact with them. Check over
@ css-tricks, they've got a profile.

**Comment by Supernova3339** [comment]
Alright. I've done my research.
Here's his [twitter](https://twitter.com/tahmidhasib)
You could contact him here, and let him know you are interested in continuing the halfmoonui project. 
In case you're wondering how I got his information, and how I can confirm it's true, there are other articles linked under his name, and his own twitter promoted the product. Take action while you still can.

**Comment by xy0** [comment]
Maybe this is the most active fork:

https://github.com/ksenginew/fullmoon

I haven't looked into it to see what all is changed.

**Comment by Supernova3339** [comment]
It's publicly archived

**Comment by JTorresConsulta** [comment]
Whats happened with the documentation ... ? 
Is the project over?
Could you public the documentation please?
Thank you

**Comment by FlavioSuarez** [comment]
There is https://github.com/ThaUnknown/quartermoon too... It seems alive...

**Comment by Supernova3339** [comment]
Interesting

**Comment by reashetyrr** [comment]
hey i ran into the same issue, i decided to (for the time being) host the documentation so we can look up the information about the project: https://halfmoondocs.reashetyr.software/

i do not intend to claim i own anything i just want to host the documentation for now while they figure it all out <3

**Comment by JTorresConsulta** [comment]
> hey i ran into the same issue, i decided to (for the time being) host the documentation so we can look up the information about the project: https://halfmoondocs.reashetyr.software/
> 
> i do not intend to claim i own anything i just want to host the documentation for now while they figure it all out <3

Thank you! 
Could you share a .zip with the docs? 

We developed a project with this framework and we are afraid that the documentation will disappear.

**Comment by FlavioSuarez** [comment]
Here at work we are in the same situation...

**Comment by reashetyrr** [comment]
I can zip it tomorrow guys sure

**Comment by reashetyrr** [comment]
I also send a mail like quite some months ago asking about the state and if perhaps if it wou5be abondoned I could take over the project, unfortunately no response (yet)

**Comment by reashetyrr** [comment]
zip file: https://halfmoondocs.reashetyr.software/halfmoondocs.zip

**Comment by JTorresConsulta** [comment]
Thank you! but why the visualization is incorrect? the links seem broken in all the pages

**Comment by reashetyrr** [comment]
That is because you load it in like file:// it's made for hosting using something like apache

**Comment by reashetyrr** [comment]
Also just send another email with the question if I could take over the half-moon project

**Comment by reashetyrr** [comment]
> There is https://github.com/ThaUnknown/quartermoon too... It seems alive...

this one unfortuantely has not been updated in atleast 5 months, i think we should see if we can inherit this amazing framework and continue work on it, potentially rewrite it so it uses a css precompiler + ts etc :)

**Comment by Supernova3339** [comment]
> > There is https://github.com/ThaUnknown/quartermoon too... It seems alive...
> 
> this one unfortuantely has not been updated in atleast 5 months, i think we should see if we can inherit this amazing framework and continue work on it, potentially rewrite it so it uses a css precompiler + ts etc :)

Halfmoon works with TS, use the NPM library

**Comment by reashetyrr** [comment]
iknow it works with ts, but i mean make the source in ts and include a dist directory containing the parsed ts for use on the web

**Comment by JTorresConsulta** [comment]
> That is because you load it in like file:// it's made for hosting using something like apache

No way. I uploaded to an apache server and the problem is the same.
Could you review it please? :)

**Comment by reashetyrr** [comment]
seems like some links are like: `/static/somefile.css` this will direct towards pumpydumpy.com and not to pumpydumpy.com/halfmoon, you might need to go through all the files to update every html file and change references to be like: `./static/somefile.css`.

the . indicates the current directory thus refering to https://pumpydumpy.com/halfmoon or make it a subdomain then / refers to https://halfmoon.pumpydumpy.com where i used halfmoon as the subdomain

> > That is because you load it in like file:// it's made for hosting using something like apache
> 
> No way. I uploaded to an apache server and the problem is the same. https://pumpydumpy.com/halfmoon/
> 
> Could you review it please? :)

**Comment by reashetyrr** [comment]
@JTorresConsulta you can add this piece of code to each html file, do change the base_url to be(in your case) `https://pumpydumpy.com/halfmoon`

`<script>
    const base_url = 'http://yourbaseurl.com/halfmoondocslocation';
    document.querySelectorAll('[src^="/"]').forEach(n => n.setAttribute('src', `${base_url}${n.getAttribute('src')}`));
    document.querySelectorAll('[href^="/"]').forEach(n => n.setAttribute('href', `${base_url}${n.getAttribute('href')}`));
</script>`

**Comment by reashetyrr** [comment]
yea but the pathname for /docs is including the /docs part, while the static folder is 1 folder up



> > @JTorresConsulta you can add this piece of code to each html file, do change the base_url to be(in your case)
> 
> Thank you @reashetyrr
> 
> For any domain replace your base_url by the window.location.origin and pathname:
> 
> `const base_url = window.location.origin + window.location.pathname;`

**Comment by reashetyrr** [comment]
which is why i suggest manually setting base_url to your host :)

**Comment by JTorresConsulta** [comment]
Ok, I rewrote the routes to work in a server without scripts
I have removed google analytics too.

Please download it, I don't know how long it will stay in that domain
https://pumpydumpy.com/halfmoon_routes.zip

**Comment by reashetyrr** [comment]
let me check, i might upload that zip on my domain if it is good :), until i receive a takedown notice i will definitely keep it up



> Ok, I rewrote the routes to work in a server without scripts I have removed google analytics too.
> 
> Please download it, I don't know how long it will stay in that domain https://pumpydumpy.com/halfmoon_routes.zip

**Comment by JTorresConsulta** [comment]
Its all right now
https://pumpydumpy.com/halfmoon_routes.zip

**Comment by reashetyrr** [comment]
now it wont work if you use a subfolder like you do, / refers to the main domain you would want ./

> Its all right now https://pumpydumpy.com/halfmoon_routes.zip

**Comment by FlavioSuarez** [comment]
Halfmoon documentation and site are available again!
