### ISSUE TITLE
Typo in dropdowns page code snippet

### ISSUE THREAD

**Issue by guites** [halfmoonui/halfmoon#143]
Hello! Thank you so much for this repo, I love how halfmoon looks on my projects.

Opening this quick issue as I haven't seen a button to help editting the documentation.

There's a miss-match in the tags provided on the Dropdowns > Overview example at <https://www.gethalfmoon.com/docs/dropdowns/#overview>

![Screenshot 2023-11-11 at 14 38 25](https://github.com/halfmoonui/halfmoon/assets/71985299/58438e07-5df1-426b-a1b2-9c291a087162)

If this kind of feedback is welcome I can keep an eye out for other stuff since I've been paying close attention to the docs lately (switching between a bootstrap based project and a tailwind one 😅 )

Hope you're well. See ya

**Comment by halfmoonui** [comment]
This has been fixed, thank you! @guites
