### ISSUE TITLE
fixed navbar with fixed footer

### ISSUE THREAD

**Issue by a1git** [halfmoonui/halfmoon#17]
Hi, 

how to get something like this ? 
https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/

**Comment by halfmoonui** [comment]
Please use the starter template generator and select the first two options: [https://www.gethalfmoon.com/docs/page-building/#starter-template-generator](https://www.gethalfmoon.com/docs/page-building/#starter-template-generator)

Short explanation: you need to add both the `.with-navbar` class and the `.with-navbar-fixed-bottom` class to the page wrapper. After that, just define the `.navbar` and the `.navbar.navbar-fixed-bottom` inside of it.
