### ISSUE TITLE
Rounded buttons

### ISSUE THREAD

**Issue by alex3025** [halfmoonui/halfmoon#25]
Will rounded buttons be added?

And, thanks for this beautiful framework!

**Comment by halfmoonui** [comment]
Seems like a good idea, I will mark it.

**Comment by halfmoonui** [comment]
@alex3025 This has been added in v1.1.1: https://www.gethalfmoon.com/docs/buttons/#rounded-buttons

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue. Thank you.
