### ISSUE TITLE
window.onscroll method not firing in js.

### ISSUE THREAD

**Issue by appventor** [halfmoonui/halfmoon#26]
Hello, I wanted to shrink the navbar on scroll by using js function 

window.onscroll = function () {
        console.log("onscroll");
        scrollFunction(); //handling navbar height according to scroll value from top using document.body.scrollTop()
      };

but it never gets triggered. is it because of page-wrapper? i dont get any error. Can you help me with this?

**Comment by halfmoonui** [comment]
This is a good question and you are on the right track. Halfmoon uses a page wrapper for the different sections and a content wrapper for the content. What you are actually scrolling is the content wrapper. So the following is a possible fix:

```html
<div class="page-wrapper">
    <div class="content-wrapper" onscroll="scrollFunction()">
        ...
    </div>
</div>
```

**Comment by appventor** [comment]
Ok thank you for the quick response. Its working as expected now.
