### ISSUE TITLE
npm install and custom build

### ISSUE THREAD

**Issue by sheriffmarley** [halfmoonui/halfmoon#3]
Hello,

first of all nice framework, but would it be possible to add the possibility to include it through npm? 
Also it would be great if you could provide the pre-proccesed files, so we could modify it more easy.

**Comment by halfmoonui** [comment]
Regarding npm, the package is already published. I have yet to update the docs. You can find it here: [https://www.npmjs.com/package/halfmoon](https://www.npmjs.com/package/halfmoon)

**Comment by Shanzid01** [comment]
What I think he means is something like `npm install halfmoon-ui`.

Also, is there any plans for Typescript support?

**Comment by halfmoonui** [comment]
> Also, is there any plan for Typescript support?

Not as of right now. However, the actual JS file is pretty small (486 lines) so it should not be **very** hard to do.

**Comment by halfmoonui** [comment]
The npm package has been published, and the docs have been updated. I will go ahead and close this issue. Please raise more issues if you feel there is need. Thank you.
