### ISSUE TITLE
FR: highlight.js Theme

### ISSUE THREAD

**Issue by Jadie-Wadie** [halfmoonui/halfmoon#35]
The [code][docs] page of the docs mentions a custom theme for [hightlight.js][highlight].
I noticed that the theme is loaded from [here][file].
It would be nice if this could be included in Halfmoon somehow, possibly as an extra file.

[docs]: https://www.gethalfmoon.com/docs/code/
[highlight]: https://highlightjs.org/
[file]: https://www.gethalfmoon.com/static/site/css/halfmoon-highlight-js-theme.css

**Comment by halfmoonui** [comment]
I don't think it should be part of the main repository. But I might put it up in a separate one.

**Comment by Jadie-Wadie** [comment]
Sounds great. If you could publish it to NPM too, maybe as `halfmoon-highlight` that would be really useful.
If you want me to help somehow, I'd be happy to.

**Comment by Jadie-Wadie** [comment]
I've created a [repo](https://github.com/Jadie-Wadie/halfmoon-highlight) and published an NPM [package](https://www.npmjs.com/package/halfmoon-highlight). If you want, you could add it to the documentation.
