### ISSUE TITLE
Set up GitHub actions for this repository

### ISSUE THREAD

**Issue by AryanBeezadhur** [halfmoonui/halfmoon#40]
[GitHub actions](https://docs.github.com/en/actions/getting-started-with-github-actions) provides some handy tools which open-source repositories like this one would greatly benefit from.

The following would help you handle issues and pull requests more easily, including closing/deleting stale issues and pull requests, greeting new contributors, and automatically labelling pull requests:

![image](https://user-images.githubusercontent.com/34424160/92758882-14018580-f387-11ea-8e03-fe3d988982aa.png)

**Comment by halfmoonui** [comment]
I am aware of Github actions. When the time is right, I will add them to this repo.
