### ISSUE TITLE
Change of cookie to local-storage

### ISSUE THREAD

**Issue by obonyojimmy** [halfmoonui/halfmoon#46]
Leverage use local-storage `window.localStorage()` for storing internal states instead of cookies.

**Comment by wopian** [comment]
Possible duplicate of https://github.com/halfmoonui/halfmoon/issues/30

**Comment by halfmoonui** [comment]
Yep, this is a duplicate of https://github.com/halfmoonui/halfmoon/issues/30. Please refer to that issue where this has been discussed and resolved.
