### ISSUE TITLE
Firefox on Android shows a white bar

### ISSUE THREAD

**Issue by simonlayfield** [halfmoonui/halfmoon#50]
I visited the documentation today and noticed a white bar appear at the bottom of the documentation pages.

I don't actually have a means of investigating further right now (I can't replaicate it in the desktop browser) but figured I'd add it here in case it's of any help. It appears when scrolling down, but then disappears when scrolling back up.

I looks as though it's positioned offscreen.

Firefox (81.1.1) for Android.

![Screenshot_20200923-180414](https://user-images.githubusercontent.com/2576361/94048167-fee71680-fdca-11ea-9fa3-19ec4ad09fd7.jpg)

(I've had to modify this screenshot to show it properly)

Screen recording here:
https://streamable.com/1zrcg8

**Comment by halfmoonui** [comment]
Thank you for the detailed issue with the video. I tested it with Firefox on Android, and could not reproduce it. Here's a video: https://streamable.com/f1a2ud

For whatever reason, the address bar on your phone does not render properly. The white bar you are seeing is not part of Halfmoon, but the browser app instead.

**Comment by simonlayfield** [comment]
Ah ok, gotcha.

Glat to know it's unrelated!
