### ISSUE TITLE
Make custom switch with animation

### ISSUE THREAD

**Issue by Peter-The-Great** [halfmoonui/halfmoon#56]
I would like to make suggestion that we should ad a transition frame for the .custom-switch label:after class.
It would kinda look like this in the css file

.custom-switch label:after{
    content: "";
    position: absolute;
    height: 1.2rem;
    width: 1.2rem;
    top: 0.4rem;
    left: 0.5rem;
    background-color: rgba(0, 0, 0, 0.2);
    border: 0 solid rgba(0, 0, 0, 0.2);
    border-radius: 50%;
    -webkit-transition: .4s;
    transition: .4s;
}
I would like to see that added in the future, i have tried to implement it but i am not good with the variables file of halfmoon.
So can i ask if anyone would like to add that to the framework.

Thank in advance

**Comment by larsjarred9** [comment]
I feel like this feature will trash the frimework since it will not add anything that can't be created with plain css that anyone can edit themself.

-1

**Comment by Peter-The-Great** [comment]
No u

**Comment by halfmoonui** [comment]
This was addressed in https://github.com/halfmoonui/halfmoon/issues/42, so I will close this.
