### ISSUE TITLE
Request: button loading state

### ISSUE THREAD

**Issue by naiba** [halfmoonui/halfmoon#64]
Hi there, can we create a loading state for buttons?

**Comment by halfmoonui** [comment]
Hey, are you talking about a JS implementation? Or just a spinner inside buttons?

**Comment by naiba** [comment]
@halfmoonui  Like this: https://u.nu/ug4kl , just CSS implmentation.

**Comment by halfmoonui** [comment]
Yes. I am planning to add spinner components soon, so loading buttons should be part of that update.

**Comment by tqwewe** [comment]
@halfmoonui is this no longer a feature? I also would love loading button states, as well as icon buttons.
