### ISSUE TITLE
Add flex-box utility class for justify-content: space-evenly

### ISSUE THREAD

**Issue by mansguiche** [halfmoonui/halfmoon#67]
There are classes for all the possible values of flex box's `justify-content` property except for the value `space-evenly`.

proposed solution:
```
.justify-content-evenly {
  -ms-flex-pack: space-evenly;
  justify-content: space-evenly;
}
```
and the relevant equivalents for the various break point media queries.

**Comment by Supernova3339** [comment]
apparantly
