### ISSUE TITLE
Docs spelling error

### ISSUE THREAD

**Issue by EddiesTech** [halfmoonui/halfmoon#72]
There's a spelling error in the example code at this section of the documentation:
https://www.gethalfmoon.com/docs/flex-utilities/#align-items

**Comment by EddiesTech** [comment]
```
<div class="d-flex align-tiems-stretch">
```
should be
```
<div class="d-flex align-items-stretch">
```

**Comment by halfmoonui** [comment]
Fixed. Thanks a lot for bringing this up!
