### ISSUE TITLE
Default Sidebar setting

### ISSUE THREAD

**Issue by begrafx** [halfmoonui/halfmoon#93]
Starting with the code from gethalfmoon.com, I've put my page together. However, I find that every time I refresh the page, the sidebar returns to the "open" position. I may be missing it, but I've gone through the documentation on the site, as well as the code of my own page, and I am not able to find anything. How do I change the (apparently default) setting for the sidebar, so that it opens in the "closed" position?

**Comment by richardoey** [comment]
Do you mean, you want it to be hidden as default? Based on the docs [here](https://www.gethalfmoon.com/docs/sidebar/#toggling-sidebar), add the `data-sidebar-hidden="hidden"` property inside the `div` wrapper. 
So, it should be like this

`<div class="page-wrapper with-navbar with-sidebar with-transitions" data-sidebar-hidden="hidden">`

**Comment by begrafx** [comment]
Thank you. Somehow I must have looked right overtop of that. Thank you for your help.
