### ISSUE TITLE
-webkit-details-marker is deprecated

### ISSUE THREAD

**Issue by richardoey** [halfmoonui/halfmoon#96]
`[Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead`
I've got this warning when using google chrome (version 89). I see halfmoon put below code. I don't know whether this change will affect a lot or not in the future. 
```
.collapse-header::-webkit-details-marker {
    /* Chrome */
    display: none;
}
```

**Comment by nabn** [comment]
see: https://github.com/GoogleChrome/lighthouse/issues/12089
