### ISSUE TITLE
Switch from using cookies to localStorage

### ISSUE THREAD

**Issue by SiddharthShyniben** [halfmoonui/halfmoon#98]
I just read through your javascript and saw that you are using `cookies` for storing the preferred theme. Why not use `localStorage`? 

`Cookies` and `localStorage` serve different purposes. `Cookies` are primarily for reading **server-side**, `localStorage` can only be read by the **client-side**. So the question is, in halfmoon, who needs this data — the client or the server? The answer is the client.

You're wasting bandwidth by sending all the data in each HTTP header by using cookies.

Is there any compatibility issue? It's [pretty much supported everywhere.](https://caniuse.com/?search=localStorage)

See [this](https://stackoverflow.com/questions/3220660/local-storage-vs-cookies) for more info.

So, by all means move to `localStorage`.

**Comment by Toby222** [comment]
#30

**Comment by SiddharthShyniben** [comment]
I see. Maybe it's better after all. I think i will just modify the js file for my own purposes
